/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Move } from "./Move";
import { MoveCountArgs } from "./MoveCountArgs";
import { MoveFindManyArgs } from "./MoveFindManyArgs";
import { MoveFindUniqueArgs } from "./MoveFindUniqueArgs";
import { CreateMoveArgs } from "./CreateMoveArgs";
import { UpdateMoveArgs } from "./UpdateMoveArgs";
import { DeleteMoveArgs } from "./DeleteMoveArgs";
import { Game } from "../../game/base/Game";
import { Player } from "../../player/base/Player";
import { MoveService } from "../move.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Move)
export class MoveResolverBase {
  constructor(
    protected readonly service: MoveService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Move",
    action: "read",
    possession: "any",
  })
  async _movesMeta(
    @graphql.Args() args: MoveCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Move])
  @nestAccessControl.UseRoles({
    resource: "Move",
    action: "read",
    possession: "any",
  })
  async moves(@graphql.Args() args: MoveFindManyArgs): Promise<Move[]> {
    return this.service.moves(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Move, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Move",
    action: "read",
    possession: "own",
  })
  async move(@graphql.Args() args: MoveFindUniqueArgs): Promise<Move | null> {
    const result = await this.service.move(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Move)
  @nestAccessControl.UseRoles({
    resource: "Move",
    action: "create",
    possession: "any",
  })
  async createMove(@graphql.Args() args: CreateMoveArgs): Promise<Move> {
    return await this.service.createMove({
      ...args,
      data: {
        ...args.data,

        game: args.data.game
          ? {
              connect: args.data.game,
            }
          : undefined,

        player: args.data.player
          ? {
              connect: args.data.player,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Move)
  @nestAccessControl.UseRoles({
    resource: "Move",
    action: "update",
    possession: "any",
  })
  async updateMove(@graphql.Args() args: UpdateMoveArgs): Promise<Move | null> {
    try {
      return await this.service.updateMove({
        ...args,
        data: {
          ...args.data,

          game: args.data.game
            ? {
                connect: args.data.game,
              }
            : undefined,

          player: args.data.player
            ? {
                connect: args.data.player,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Move)
  @nestAccessControl.UseRoles({
    resource: "Move",
    action: "delete",
    possession: "any",
  })
  async deleteMove(@graphql.Args() args: DeleteMoveArgs): Promise<Move | null> {
    try {
      return await this.service.deleteMove(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Game, {
    nullable: true,
    name: "game",
  })
  @nestAccessControl.UseRoles({
    resource: "Game",
    action: "read",
    possession: "any",
  })
  async getGame(@graphql.Parent() parent: Move): Promise<Game | null> {
    const result = await this.service.getGame(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Player, {
    nullable: true,
    name: "player",
  })
  @nestAccessControl.UseRoles({
    resource: "Player",
    action: "read",
    possession: "any",
  })
  async getPlayer(@graphql.Parent() parent: Move): Promise<Player | null> {
    const result = await this.service.getPlayer(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
